name: l10n-sync-zh-Hans

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync-status-zh-Hans:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download mdlm
      run: curl -o- https://raw.githubusercontent.com/markdown-localization/mdlm-sh/v0.0.17/install.sh | bash      
      
    - name: Sync status - zh-Hans
      run: |
        $HOME/.mdlm/mdlm.sh diff zh-Hans
