name: l10n-sync-ar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync-status-ar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download mdlm
      run: curl -o- https://raw.githubusercontent.com/markdown-l10n/mdlm-sh/v0.0.8/install.sh | bash

    - name: Sync status - ar
      run: |
        export TERM=xterm-256color
        $HOME/.mdlm/mdlm.sh status ar --diff
