name: l10n-sync-fr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync-status-fr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download mdlm
      run: curl -o- https://raw.githubusercontent.com/markdown-l10n/mdlm-sh/v0.0.7/install.sh | bash
      
    - name: Sync status - fr
      run: |
        export TERM=xterm-256color
        $HOME/.mdlm/mdlm.sh status fr --diff
