name: l10n-sync-es

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync-status-es:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download mdlm
      run: curl -o- https://raw.githubusercontent.com/markdown-localization/mdlm-sh/v0.0.15/install.sh | bash

    - name: Sync status - es
      run: |
        $HOME/.mdlm/mdlm.sh status es --diff
